import path from "path";

export const items = [
  {
    series: "",
    name: "Flights Tracker",
    type: "Product",
    categories: ["UI", "Motion"],
    description:
      "Track your flights and get real-time updates on delays, cancellations, and gate changes.",
    year: "2026",
    asset: "/previews/flights.png",
    path: "/flights",
    isNew: false,
  },
  {
    series: "",
    name: "Sunrise/Sunset",
    type: "Interaction",
    categories: ["Web", "Visual Design"],
    description:
      "A sunrise/sunset component that shows the current time of day and the time until the next sunrise or sunset.",
    year: "2026",
    asset: "",
    path: "/sunrise-sunset",
    isNew: true,
  },
  {
    series: "",
    name: "3d carousel",
    type: "Interaction",
    categories: ["Web"],
    description:
      "A 3D carousel component that allows users to navigate through a collection of items in a three-dimensional space.",
    year: "2024",
    asset: "/previews/3d-carousel.png",
    path: "/3d-carousel",
    isNew: false,
  },
  {
    series: "",
    name: "Text load in",
    type: "Interaction",
    categories: ["Motion"],
    description:
      "A text load in component that allows users to visualize text animations in a three-dimensional space.",
    year: "2024",
    asset: "",
    path: "/text-load-in",
    isNew: false,
  },
  {
    series: "Charts",
    name: "Artist selector",
    type: "Video",
    categories: ["UI", "Motion"],
    description:
      "An artist selector component for a music player app that allows users to select their favorite artists and view their discography.",
    year: "2023",
    asset: "/artist-selector.mp4",
    path: null,
    isNew: false,
  },
  {
    series: "Tags",
    name: "Multi-select",
    type: "Product",
    categories: ["UI", "Motion"],
    description:
      "A tag/multiselect component that allows users to select multiple options from a list.",
    year: "2025",
    asset: "/previews/multiselect.png",
    path: "/multiselect",
    isNew: false,
  },
  {
    series: "Tags",
    name: "Single-select",
    type: "Product",
    categories: ["UI"],
    description:
      "A tag/single select component that allows users to select a single option from a list.",
    asset: "/previews/singleselect.png",
    year: "2025",
    path: "/singleselect",
    isNew: false,
  },
  {
    series: "Car UI",
    name: "Temperature control",
    type: "Interaction",
    categories: ["Motion"],
    description:
      "A temperature control component for a car's climate control system.",
    asset: "/previews/car-temperature.png",
    year: "2024",
    path: "/car-temperature",
    isNew: false,
  },
  {
    series: "Car UI",
    name: "Sound control",
    type: "Interaction",
    categories: ["Motion"],
    description: "A sound control component for a car's audio system.",
    asset: "",
    year: "2024",
    path: "/car-sound",
    isNew: false,
  },
  {
    series: "Skeumorphic",
    name: "Button toggle",
    type: "Interaction",
    categories: ["Visual Design"],
    description:
      "A skeumorphic toggle switch that mimics the look and feel of a physical toggle switch.",
    asset: "",
    year: "2024",
    path: "/skeumorphic-button-toggle",
    isNew: false,
  },
  {
    series: "Skeumorphic",
    name: "Dark toggle",
    type: "Interaction",
    categories: ["Visual Design"],
    description:
      "A skeumorphic dark mode toggle that mimics the look and feel of a physical toggle switch.",
    asset: "",
    year: "2024",
    path: "/skeumorphic-dark-toggle",
    isNew: false,
  },
  {
    series: "",
    name: "Signature animation",
    type: "Product",
    categories: ["UI", "Motion"],
    description:
      "A signature animation that can be used to add a personal touch to a website or app.",
    asset: "",
    year: "2024",
    path: "/signature-animation",
    isNew: false,
  },
  {
    series: "Music player",
    name: "Album surfer",
    type: "Product",
    categories: ["UI", "Motion"],
    description: "An album surfer component for a music player app.",
    asset: "",
    year: "2025",
    path: "/album-surfer",
    isNew: false,
  },
  // {
  //   series: "Music player",
  //   name: "Volume control",
  //   type: "UI",
  //   description: "A volume control component for a music player app.",
  //   asset: "/volume-control.jpg",
  //   year: "",
  //   path: "/volume-control",
  // },
  {
    series: "Music player",
    name: "Album scroller",
    type: "Product",
    categories: ["UI", "Motion"],
    description: "An album scroller component for a music player app.",
    asset: "",
    year: "2025",
    path: "/album-scroller",
    isNew: false,
  },
  {
    series: "Music player",
    name: "Album selector",
    type: "Product",
    categories: ["UI", "Motion"],
    description: "An album selector component for a music player app.",
    asset: "",
    year: "2024",
    path: "/album-selector",
    isNew: false,
  },
  {
    series: "Music player",
    name: "Album carousel",
    type: "Product",
    categories: ["Motion"],
    description: "An album carousel component for a music player app.",
    asset: "",
    year: "2024",
    path: "/album-carousel",
    isNew: false,
  },
  {
    series: "Music player",
    name: "Album grid",
    type: "Product",
    categories: ["UI", "Web"],
    description: "An album grid component for a music player app.",
    asset: "",
    year: "2024",
    path: "/album-grid",
    isNew: false,
  },
  {
    series: "Music player",
    name: "Modal open",
    type: "Product",
    categories: ["UI", "Motion"],
    description: "A modal open component for a music player app.",
    asset: "",
    year: "2024",
    path: "/modal-open",
    isNew: false,
  },
  {
    series: "",
    name: "Pill load-in",
    type: "Interaction",
    categories: ["Motion"],
    description:
      "A pill load-in component that can be used to show loading states in a visually appealing way.",
    asset: "",
    year: "2023",
    path: "/pill-load-in",
    isNew: false,
  },
  {
    series: "Pursuit",
    name: "Bubble filters",
    type: "Video",
    categories: ["UI", "Motion"],
    description:
      "A video showcasing bubble filters, a unique and visually appealing way to filter content.",
    asset: "/bubble-filters.mp4",
    year: "2023",
    path: null,
    isNew: false,
  },
  {
    series: "Pursuit",
    name: "Layer selection",
    type: "Video",
    categories: ["UI", "Motion"],
    description:
      "A video showcasing layer selection, a powerful tool for selecting and manipulating layers in a design or editing software.",
    asset: "/layer-selection.mp4",
    year: "2023",
    path: null,
    isNew: false,
  },
  {
    series: "Pursuit",
    name: "Compass",
    type: "Video",
    categories: ["Visual Design", "Motion"],
    description:
      "A video showcasing a compass, a navigational instrument that shows direction relative to the Earth's magnetic poles.",
    asset: "/compass.mp4",
    year: "2023",
    path: null,
    isNew: false,
  },
];
