import path from "path";

export const items = [
  {
    series: "Tags",
    name: "Dynamic multi-select",
    type: "Product",
    categories: ["UI", "Motion"],
    year: "2026",
    preview: "/previews/dynamic-select.png",
    path: "/dynamic-select",
    color: "transparent",
  },
  {
    series: "",
    name: "Dynamic Contents",
    type: "Interaction",
    categories: ["Web", "Motion"],
    year: "2026",
    preview: "/previews/dynamic-contents.png",
    path: "/dynamic-contents",
    isNew: true,
    color: "#fff",
  },
  // {
  //   series: "",
  //   name: "Sunrise/Sunset",
  //   type: "Interaction",
  //   categories: ["Web", "Visual Design"],
  //   year: "2026",
  //   preview: "",
  //   path: "/sunrise-sunset",
  //   isNew: true,
  //   color: "transparent",
  // },
  {
    series: "",
    name: "3d carousel",
    type: "Interaction",
    categories: ["Web"],
    year: "2024",
    preview: "/previews/3d-carousel.png",
    path: "/3d-carousel",
    color: "#fff",
  },
  // {
  //   series: "",
  //   name: "Text load in",
  //   type: "Interaction",
  //   categories: ["Motion"],
  //   year: "2024",
  //   preview: "",
  //   path: "/text-load-in",
  //   color: "#000"
  // },
  {
    series: "Charts",
    name: "Artist select",
    type: "Video",
    categories: ["UI", "Motion"],
    year: "2023",
    preview: "/previews/artist-select.png",
    video: "/videos/artist-select.mp4",
    path: "/artist-select",
    color: "#000",
  },
  {
    series: "Tags",
    name: "Multi-select",
    type: "Product",
    categories: ["UI", "Motion"],
    year: "2025",
    preview: "/previews/multiselect.png",
    path: "/multiselect",
    color: "#070A0E",
  },
  {
    series: "Tags",
    name: "Single-select",
    type: "Product",
    categories: ["UI"],
    preview: "/previews/singleselect.png",
    year: "2025",
    path: "/singleselect",
    color: "#070A0E",
  },
  {
    series: "Car UI",
    name: "Temperature control",
    type: "Interaction",
    categories: ["Motion"],
    preview: "/previews/car-temperature.png",
    year: "2024",
    path: "/car-temperature",
    color: "#000",
  },
  {
    series: "Car UI",
    name: "Sound control",
    type: "Interaction",
    categories: ["Motion"],
    preview: "/previews/car-sound.png",
    year: "2024",
    path: "/car-sound",
    color: "#000",
  },
  {
    series: "Skeumorphic",
    name: "Button toggle",
    type: "Interaction",
    categories: ["Visual Design"],
    preview: "/previews/button-toggle.png",
    year: "2024",
    path: "/button-toggle",
    color: "#fff",
  },
  {
    series: "Skeumorphic",
    name: "Flashlight",
    type: "Interaction",
    categories: ["Visual Design"],
    preview: "/previews/flashlight.png",
    year: "2024",
    path: "/flashlight",
    color: "#000",
  },
  {
    series: "",
    name: "Signature animation",
    type: "Product",
    categories: ["UI", "Motion"],
    preview: "/previews/signature.png",
    year: "2024",
    path: "/signature",
    color: "transparent",
  },
  {
    series: "",
    name: "Album surfer",
    type: "Product",
    categories: ["UI", "Motion"],
    preview: "/previews/album-surfer.png",
    year: "2025",
    path: "/album-surfer",
    color: "#fff",
  },
  // {
  //   series: "Music player",
  //   name: "Volume control",
  //   type: "UI",
  //   description: "A volume control component for a music player app.",
  //   preview: "/volume-control.jpg",
  //   year: "",
  //   path: "/volume-control",
  // },
  {
    series: "Music player",
    name: "Album scroller",
    type: "Product",
    categories: ["UI", "Motion"],
    preview: "",
    year: "2025",
    path: "/album-scroller",
  },
  {
    series: "Music player",
    name: "Album selector",
    type: "Product",
    categories: ["UI", "Motion"],
    preview: "",
    year: "2024",
    path: "/album-selector",
  },
  {
    series: "Music player",
    name: "Album carousel",
    type: "Product",
    categories: ["Motion"],
    preview: "",
    year: "2024",
    path: "/album-carousel",
  },
  {
    series: "",
    name: "Stack / Grid toggle",
    type: "Product",
    categories: ["UI", "Web"],
    preview: "/previews/stack-grid.png",
    year: "2024",
    path: "/stack-grid",
    color: "#444444",
  },
  {
    series: "",
    name: "Modal open",
    type: "Product",
    categories: ["UI", "Motion"],
    preview: "/previews/modal-open.png",
    year: "2024",
    path: "/modal-open",
    color: "#161616",
  },
  {
    series: "",
    name: "Pill load-in",
    type: "Interaction",
    categories: ["Motion"],
    preview: "",
    year: "2023",
    path: "/pill-load-in",
  },
  {
    series: "",
    name: "Cards hover",
    type: "Interaction",
    categories: ["Web"],
    preview: "/previews/cards-hover.png",
    year: "2024",
    path: "/cards-hover",
    color: "#fff",
  },
  {
    series: "Superpower.com",
    name: "List selection",
    type: "Video",
    categories: ["UI", "Web"],
    preview: "/previews/list-selection.png",
    video: "/videos/list-selection.mov",
    year: "2024",
    path: "/list-selection",
    color: "#fff",
  },
  {
    series: "Superpower.com",
    name: "Group selection",
    type: "Video",
    categories: ["UI", "Web", "Motion"],
    preview: "/previews/group-selection.png",
    video: "/videos/group-selection.mp4",
    year: "2024",
    path: "/group-selection",
    color: "#fff",
  },
  {
    series: "Superpower.com",
    name: "Categories selection",
    type: "Video",
    categories: ["UI", "Web", "Motion"],
    preview: "/previews/categories-selection.png",
    video: "/videos/categories-selection.mp4",
    year: "2024",
    path: "/categories-selection",
    color: "#fff",
  },
  {
    series: "Superpower.com",
    name: "Areas selection",
    type: "Video",
    categories: ["UI", "Web", "Motion"],
    preview: "/previews/areas-selection.png",
    video: "/videos/areas-selection.mp4",
    year: "2024",
    path: "/areas-selection",
    color: "#fff",
  },
  {
    series: "Pursuit",
    name: "Bubble filters",
    type: "Video",
    categories: ["UI", "Motion"],
    preview: "/previews/bubble-filters.png",
    video: "/videos/bubble-filters.mp4",
    year: "2023",
    path: "/bubble-filters",
    color: "#CEDFF6",
  },
  {
    series: "Pursuit",
    name: "Layer selection",
    type: "Video",
    categories: ["UI", "Motion"],
    preview: "/previews/layer-selection.png",
    video: "/videos/layer-selection.mp4",
    year: "2023",
    path: "/layer-selection",
    color: "#CEDFF6",
  },
  {
    series: "Pursuit",
    name: "Compass",
    type: "Video",
    categories: ["Visual Design", "Motion"],
    preview: "/previews/compass.png",
    video: "/videos/compass.mp4",
    year: "2023",
    path: "/compass",
    color: "#CEDFF6",
  },
  {
    series: "",
    name: "Light/Dark Scroll",
    type: "Video",
    categories: ["Visual Design", "Motion"],
    preview: "/previews/light-dark-scroll.png",
    video: "/videos/light-dark-scroll.mp4",
    year: "2023",
    path: "/light-dark-scroll",
    color: "#fff",
  },
];
